### ISSUE TITLE
New feature : pass encoding options to underneath flac command

### ISSUE THREAD

**Issue by Siltaar** [chungy/reflac#2]
This would allow to recode a 96kHz flac file to 48kHz with the flac encode `--sample-rate=#` option.

**Comment by Siltaar** [comment]
Well, seems compromised : 

    ERROR: raw format options (--endian, --sign, --channels, --bps, and --sample-rate) are not allowed for non-raw input

**Comment by chungy** [comment]
Those options are to pass in raw (headerless) PCM data to FLAC, and it has no way otherwise to know any of the properties of the file.

You'll need to rely on external tools like `sox` or `ffmpeg` to resample your files.

**Comment by Siltaar** [comment]
Thanks a lot for your answer. I made this little reminder of the command to use in this case (including a practical case for an album) :
http://www.grimoire-command.es/2018/resample_flac_music_using_sox.html

The command alone :
`$ sox -S <original-flac-file> -r 48000 -b 16 <final-flac-file>`
