### ISSUE TITLE
Skip intermediate decompression step

### ISSUE THREAD

**Issue by wlhlm** [chungy/reflac#6]
The README states that currently only one coverart image per flac file is supported by reflac. I have quite a few files with multiple images embedded, thus unfortunately making reflac not usable with my collection. I then looked into the code to see how hard it'll be to implement multiple embedded images and then started wondering about how reflac handles the recompression.

From what I can gleam from the code, the process works like this:
1. extract metadata (tags) and embedded images from the flac file using metaflac
2. decompress to a wav file in the TMPDIR (`flac -d`)
3. compress wav file in TMPDIR to flac file
4. tag flac file with metadata extracted in step 1

I wonder why the intermediate decompression step is necessary here? The flac tool supports recompressing existing flac files out of the box, like so:
```
flac -V -8 input.flac -o output.flac
```
This operation also preserves all metadata, making the calls to metaflac obsolete and thus would simplify reflac. This also fixes the limitation with the embedded images.

**Comment by chungy** [comment]
I think when I first made reflac, the normal flac program didn't have the capability to take in flac as input. I haven't noticed the development in being able to do so, either. (Or maybe it always had it and I've just been oblivious)

All good points, I'll check it out and see if I can refactor this thing. Shouldn't pose too much difficulty :)

**Comment by wlhlm** [comment]
Thank you for looking into it! ❤️
